/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*Q1 : Assignment 1: User Switch Controlled LED (Basic GPIO Input)
	Objective
	To understand GPIO input configuration and control an LED using a switch.
	Problem Statement
	Configure the USER switch (PA0) as input.
	Configure the Green LED (PD12) as output.
	When the switch is pressed, the LED should turn ON.
	When the switch is released, the LED should turn OFF.
	Requirements
	Use bare-metal (register-level) programming.
	Enable GPIO clocks using RCC registers.
	Use multiple source files:
	main.c
	gpio.c
	gpio.h*/



#include"gpio.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


int main(void)
{
	led_init();
	switch_init();
	while(1)
	{
		if(switch_status()==1){
			led_on();
		}
	}
}









