/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 *
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*Assignment 2: Toggle LED Using User Switch (Debouncing)
	Objective
	To implement switch debouncing and LED toggling logic.
	Problem Statement
	Use USER switch (PA0) as input.
	Use Red LED (PD14) as output.
	Each single press of the switch should toggle the LED state:
	OFF → ON
	ON → OFF
	The LED should not toggle continuously while the switch is held down.*/


#include"gpio.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


int main(void)
{
	int flag = 0;
	led_init();
	switch_init();
	LED_PORT->ODR &= ~( BV(14) );
	while(1)
	{
		if(switch_status()==1){
			GPIOD->ODR ^= BV(14);
		}
	}
}









