/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include"gpio.h"

#if !defined(_SOFT_FP) && defined(_ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


int main(void)
{
	int c ;
	led_init();
	switch_init();
	while(1)
	{
		if(switch_status()==1){
			while(switch_status()!=1);
			LED_PORT->ODR |= BV(GREEN_LED);
			DelayMs(5000);

			while(switch_status()!=1);
			LED_PORT->ODR |= BV(BLUE_LED);
			DelayMs(5000);

			while(switch_status()!=1);
			LED_PORT->ODR &= ~(BV(GREEN_LED)| BV(BLUE_LED));
			DelayMs(5000);
		}
	}
}

